### ISSUE TITLE
incompatible route with foreman.py inv script

### ISSUE THREAD

**Issue by jctanner** [ansible/foreman-test-container#3]
```
Running inventory_foreman_script integration test script
[foreman]
url = http://foreman-stub:8080
user = ansible-tester
password = secure
ssl_verify = False
/root/ansible/test/integration/targets/inventory_foreman_script
total 92
drwxrwxr-x   2 root root  4096 Oct 11 14:42 .
drwxrwxr-x 846 root root 36864 Oct 11 14:35 ..
-rw-rw-r--   1 root root    49 Oct 11 13:37 aliases
-rw-rw-r--   1 root root    86 Oct 11 13:37 ansible.cfg
-rw-r--r--   1 root root   100 Oct 11 14:42 foreman.ini
-rwxr-xr-x   1 root root 16688 Oct 11 14:42 foreman.py
-rwxrwxr-x   1 root root   952 Oct 11 14:42 runme.sh
-rw-r--r--   1 root root 12288 Oct 11 14:42 .runme.sh.swp
-rw-rw-r--   1 root root  1942 Oct 11 13:37 test_foreman_inventory.yml
Traceback (most recent call last):
  File "./foreman.py", line 441, in <module>
    sys.exit(not ForemanInventory().run())
  File "./foreman.py", line 435, in run
    self.get_inventory()
  File "./foreman.py", line 385, in get_inventory
    self.update_cache()
  File "./foreman.py", line 333, in update_cache
    self.facts[dns_name] = self._get_facts(host)
  File "./foreman.py", line 237, in _get_facts
    ret = self._get_facts_by_id(host['id'])
  File "./foreman.py", line 214, in _get_facts_by_id
    return self._get_json(url)
  File "./foreman.py", line 179, in _get_json
    ret.raise_for_status()
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: NOT FOUND for url: http://foreman-stub:8080/api/v2/hosts/1339/facts?per_page=250&page=1                                                                                         
Cleanup: removing foreman.ini...
removed 'foreman.ini'
```

**Comment by mattclay** [comment]
Closing, as this container is no longer maintained.
